apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    tag: postgres-cluster-ip-service
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    tag: postgresql-db