apiVersion: v1
kind: Pod
metadata:
  name: postgresql-db-pod
  labels:
    tag: postgresql-db
    app: demo-voting-app
spec:
  containers:
    - name: postgresql-db
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres