apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    tag: redis-db
    app: demo-voting-app
spec:
  containers:
    - name: redis-db
      image: redis
      ports:
        - containerPort: 6379