apiVersion: v1
kind: Service
metadata:
  name: result-app-nodeport-service
  labels:
    tag: result-app-nodeport-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    tag: result-app-frontend