kubectl create -f redis-pod.yaml
kubectl create -f postgresqldb-pod.yaml
kubectl create -f voting-app-pod.yaml
kubectl create -f result-app-pod.yaml
kubectl create -f worker-pod.yaml
kubectl create -f redis-service.yaml
kubectl create -f postgresqldb-service.yaml
kubectl create -f voting-app-service.yaml
kubectl create -f result-app-service.yaml