kubectl delete pod redis-pod
kubectl delete pod postgresql-db-pod
kubectl delete pod voting-app-pod
kubectl delete pod result-app-pod
kubectl delete pod worker-pod
kubectl delete service redis
kubectl delete service db
kubectl delete service voting-app-nodeport-service
kubectl delete service result-app-nodeport-service