apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    tag: worker-app
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1