kubectl delete deployment redis-deployment
kubectl delete deployment postgres-deployment
kubectl delete deployment voting-app-deployment
kubectl delete deployment result-app-deployment
kubectl delete deployment worker-deployment
kubectl delete service redis
kubectl delete service db
kubectl delete service voting-app-nodeport-service
kubectl delete service result-app-nodeport-service