apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      tag: voting-app-pod
  template:
    metadata:
      name: voting-app-pod
      labels:
        tag: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app-container
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
  replicas: 1