apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs
  namespace: website
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: mysql-nfs    

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-nfs
  namespace: website
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: wp-nfs
