apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: website
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
      name: wordpress-pod
      namespace: website
    spec:
      containers:
      - image: wordpress
        imagePullPolicy: Always
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: cm-mswp
              key: mysql-db-host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: cm-mswp
              key: wordpress-db-name
        - name: WORDPRESS_TABLE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: cm-mswp
              key: table-prefix
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: mysql-wordpress-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: mysql-wordpress-user-pass
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: /var/www/html
            name: wp-nfs
      restartPolicy: Always  
      volumes:
        - name: wp-nfs
          persistentVolumeClaim:
            claimName: wp-nfs

